# Generated by Django 4.2 on 2023-04-17 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dependapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
    ]
