# Generated by Django 4.2 on 2023-04-17 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dependapp', '0002_remove_person_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Branches',
        ),
        migrations.RenameModel(
            old_name='Country',
            new_name='Districts',
        ),
    ]
